title: MSolve.FEM
email: info@mgroup.ntua.gr
description: > # this means to ignore newlines until "baseurl:"
 Finite element analysis library for computational mechanics applications
baseurl: "/MSolve.FEM" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site

twitter_username: mgroupntua
github_username:  mgroupntua

# Build settings
markdown: kramdown

collections:
  episodes:
    output: true
  seasons:
    output: true
  characters:
    output: true

defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
      type: "seasons"
    values:
      layout: "season"

gems:
  - octopress-paginate

theme: jekyll-theme-slate
